resource_space_pull:
  resource_space:
    resource_url: 'https://siteone.resourcespace.com/api/?'
    resource_user: 'scrigger'
    resource_apikey: '3cdcfe043feafc0b6a032d5caf8629143eb588f5fdb3a24d5ea54be2f8f7da63'
  tmp_template_upload_pimcore_dir: var/tmp/
  asset_folder: 'images'
  in_progress_process_life: 360
  max_parallel_active_process_count: 2
  schedule_screen_refresh_time: 1
